# Boiler Plate for workflow from GitHub Docs
# Licence: MIT License
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [staging, main, stagingv4]
  pull_request:
    branches: [staging, main, stagingv4]
jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add service.json file
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "google-services.json"
          json: ${{ secrets.SERVICE_JSON }}
          dir: "code/app/"
      - name: Run Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2.15.0
        with:
          api-level: 23
          working-directory: ./code
          script: ./gradlew build
  run_android_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code
    steps:
      - uses: actions/checkout@v2
      - name: Add service.json file
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "google-services.json"
          json: ${{ secrets.SERVICE_JSON }}
          dir: "code/app/"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: chmod +x ./gradlew
      - name: Make Android Test Script Executable
        run: chmod +x ./android_int_test.sh
      - name: Install node.js to get access to npm
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Firestore Emulator with Gradle Task
        run: |
              npm install -g firebase-tools
              firebase emulators:exec ./android_int_test.sh

  run_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code
    steps:
      - uses: actions/checkout@v2
      - name: Add service.json file
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "google-services.json"
          json: ${{ secrets.SERVICE_JSON }}
          dir: "code/app/"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: chmod +x ./gradlew
      - name: Unit Test with Gradle
        run: ./gradlew test
