# Boiler Plate for workflow from GitHub Docs
# Licence: MIT License
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ staging, main ]
  pull_request:
    branches: [ staging, main ]
jobs:
  run_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add service.json file
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "google-services.json"
        json: ${{ secrets.SERVICE_JSON }}
        dir: 'code/app/'
    - name: Run Android Emulator
      uses: ReactiveCircus/android-emulator-runner@v2.15.0
      with:
        api-level: 23
        working-directory: ./code
        script: ./gradlew build

  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd code
    - run: chmod +x ./gradlew
    - name: Unit Test with Gradle
      run: ./gradlew test
